"""add series.poster_rel

Revision ID: 1835c50b5735
Revises: e22265d0109e
Create Date: 2025-09-21 13:22:21.683869

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1835c50b5735"
down_revision: Union[str, Sequence[str], None] = "e22265d0109e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "series", sa.Column("poster_rel", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("series", "poster_rel")
    # ### end Alembic commands ###
