"""add episode.thumb_rel

Revision ID: c750e687ac04
Revises: cda712b8b35d
Create Date: 2025-09-20 23:57:23.066109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c750e687ac04'
down_revision: Union[str, Sequence[str], None] = 'cda712b8b35d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('thumb_rel', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episodes', 'thumb_rel')
    # ### end Alembic commands ###
