"""profiles + watch_progress

Revision ID: e22265d0109e
Revises: c750e687ac04
Create Date: 2025-09-21 01:30:47.878608

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e22265d0109e"
down_revision: Union[str, Sequence[str], None] = "c750e687ac04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("avatar", sa.String(length=255), nullable=True),
        sa.Column("is_kid", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_profiles_name"), "profiles", ["name"], unique=True)
    op.create_table(
        "watch_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("episode_id", sa.Integer(), nullable=False),
        sa.Column("position_sec", sa.Float(), nullable=False),
        sa.Column("duration_sec", sa.Float(), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["episode_id"], ["episodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "profile_id", "episode_id", name="uq_progress_profile_episode"
        ),
    )
    op.create_index(
        op.f("ix_watch_progress_episode_id"),
        "watch_progress",
        ["episode_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_watch_progress_profile_id"),
        "watch_progress",
        ["profile_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_watch_progress_profile_id"), table_name="watch_progress")
    op.drop_index(op.f("ix_watch_progress_episode_id"), table_name="watch_progress")
    op.drop_table("watch_progress")
    op.drop_index(op.f("ix_profiles_name"), table_name="profiles")
    op.drop_table("profiles")
    # ### end Alembic commands ###
