name: Android Debug APK

on:
  workflow_dispatch:
  push:
    branches: [ dev, main ]
    paths:
      - 'tv-app/**'

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install npm deps
        working-directory: tv-app/tv_app
        run: npm ci

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Build Debug
        working-directory: tv-app/tv_app
        run: ./android/gradlew assembleDebug

      - name: Upload APK (debug)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: tv-app/tv_app/android/app/build/outputs/apk/debug/app-debug.apk
