name: Android Debug APK

on:
  workflow_dispatch:
  push:
    branches: [ dev, main ]
    paths:
      - 'tv-app/**'
      - '.github/workflows/android-debug.yml'
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: tv-app/tv_app/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('tv-app/tv_app/package-lock.json', 'tv-app/tv_app/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install JS deps
        working-directory: tv-app/tv_app
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          elif [ -f yarn.lock ]; then
            corepack enable
            yarn install --frozen-lockfile
          else
            npm install
          fi

      - name: (debug) RN Android CLI path
        working-directory: tv-app/tv_app
        run: node -e "console.log(require.resolve('@react-native-community/cli-platform-android/package.json'))"

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK 35
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platforms;android-35" "build-tools;35.0.0" "platform-tools" "cmdline-tools;latest"

      - name: Make gradlew executable
        working-directory: tv-app/tv_app/android
        run: chmod +x gradlew

      - name: Build Debug APK
        working-directory: tv-app/tv_app/android
        run: ./gradlew :app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: tv-app-debug-apk
          path: tv-app/tv_app/android/app/build/outputs/apk/debug/*.apk
